# 机器人配置
bot:
  host: 'localhost'
  port: 4000
  verifyKey: admin123
  qq: 123456
# 数据库配置
mysql:
  host: localhost
  port: 3306
  user: root
  password: admin123
  database: qq-bot
# 邮箱
smtp:
  host: smtp.ym.163.com
  port: 25
  # ssl
  secure: false
  from: qq-bot <ltfei@ltfei.cn>
  auth:
    user: 123456
    pass: admin123
# 腾讯云api密钥
tencentCloud:
  credential:
    secretId: AAAAAAAAAAAAAAAAAAAAAAAAAAAA
    secretKey: AAAAAAAAAAAAAAAAAAAAAAAAAAAA
# 启用的插件，不需要的可以注释，若不启用下方的配置将不会生效
plugins:
  # - hello_world
  - sql
  - send_nudge
  - friend_check
  - member_join_request
  - send_message
  - purge_cdn_cache
# 插件相关配置
# 戳一戳
# 命令发送人（可以是自己发给自己） 发送 "戳 123456 654321 10" 即可在群123456中戳654321 10次
send_nudge:
  # 命令发送人qq，可以是自己
  command_sender: 1585380249
  # 命令前缀
  command: '戳'
# 好友检测
# 按照 time 间隔表达式检测单向好友，若检测到会使用模板发送到邮箱，需要配置smtp
friend_check:
  emailTo: ltfei@ltfei.cn
  time: '*/30 * * * * *'
  path: './data/friends.json'
  templatePath: './template/friend_check.html'
# 进群自动审批，bot需要有管理权限，否则不会触发事件
# - group: 群号
#   regex: 正则表达式 用来匹配答案
#   minLevel: 最小等级
member_join_request:
  - group: 123456
    regex: '^我是答案$'
    minLevel: 16
  - group: 234567
    regex: '^[a-zA-Z0-9_]{3,15}$'
    minLevel: 16
# 定时发送消息
send_message:
  - time: '*/30 * * * * *'
    # 发送到哪些群聊
    groups: [12345, 65432]
    # 发送给哪些好友
    friends: [98765]
    # 消息模板 可在template文件夹中创建，文件会被git忽略，也可自行填写路径，相对路径相对于终端所在目录
    templatePath: './template/sendMessageHelloWorld.json'
# 刷新cdn缓存，需要配置tencentCloud
# 消息格式( <>为必填 []为选填 )：
# <命令前缀> [刷新类型 0:刷新变更资源/1:刷新全部资源] [urlEncode 0:关闭 1:开启]
# <url 一行一个，可以是下面的预设，可以是all>
# [url]
# [url]
purge_cdn_cache:
  # 命令发送人 可以是自己
  commandSender: 12345
  # 命令前缀
  command: 刷新cdn
  # 预设，使用 all 可刷新所有
  urls:
    baidu: https://www.baidu.com
    bing: https://www.bing.com
    google: https://google.com
# 数据库备份聊天记录
# 需要配置数据库
# 可配置 图片和语音的保存位置
sql_v2:
  path:
    Image: './data/Image/'
    Voice: './data/Voice/'
# 网页版qq
# 需要配置数据库
# 目前仅支持查看数据库中近期的聊天记录，后续会完善更多功能
# 使用需要升级数据库插件到 sql-v2 可执行 yarn update:sqlv2 来升级
webqq:
  # 允许跨域请求的地址
  corsOrigin: http://aofuga.localhost:5173/
  # api端口
  port: 3000
  # 网页版登录密码
  password: admin123
  # token密钥 请填写随机字符串
  jwtSecretKey: :OI#LR^YQWO*RFGUIQ#R@Q*YRFGUH#Q
  # api目录(需要在网页端配置相同路径)
  baseUrl: /api
  # token过期时间(1d表示1天)
  expiresIn: 1d
# ws异常提醒 若ws连接断开，会按照间隔时间发送到邮箱，需要配置smtp
error_message:
  emailTo: ltfei@ltfei.cn
  # 发送间隔，单位分钟
  interval: 10