# 机器人配置
bot:
  host: { bot.host }
  port: { bot.port }
  verifyKey: { bot.verifyKey }
  qq: { bot.qq }
# 数据库配置
mysql:
  host: { mysql.host }
  port: { mysql.port }
  user: { mysql.user }
  password: { mysql.password }
  database: { mysql.database }
# 邮箱
smtp:
  host: { smtp.host }
  port: { smtp.port }
  # ssl
  secure: { smtp.secure }
  from: { smtp.from }
  auth:
    user: { smtp.auth.user }
    pass: { smtp.auth.pass }
# 腾讯云api密钥
tencentCloud:
  credential:
    secretId: AAAAAAAAAAAAAAAAAAAAAAAAAAAA
    secretKey: AAAAAAAAAAAAAAAAAAAAAAAAAAAA
# 启用的插件，不需要的可以注释，若不启用下方的配置将不会生效
plugins:
  # - hello_world
  - sql
  - send_nudge
  - friend_check
  - member_join_request
  - send_message
  # - purge_cdn_cache
# 插件相关配置
# 戳一戳
# 命令发送人（可以是自己发给自己） 发送 "戳 123456 654321 10" 即可在群123456中戳654321 10次
send_nudge:
  # 命令发送人qq，可以是自己
  command_sender: { send_nudge.command_sender }
  # 命令前缀
  command: { send_nudge.command }
# 好友检测
# 按照 time 间隔表达式检测单向好友，若检测到会使用模板发送到邮箱，需要配置smtp
friend_check:
  emailTo: { friend_check.emailTo }
  time: { friend_check.time }
  path: { friend_check.path }
  templatePath: { friend_check.templatePath }
# 进群自动审批，bot需要有管理权限，否则不会触发事件
# - group: 群号
#   regex: 正则表达式 用来匹配答案
#   minLevel: 最小等级
member_join_request:
<for-member_join_request>  - group: { member_join_request.group }
    regex: { member_join_request.regex }
    minLevel: { member_join_request.minLevel }
</for-member_join_request>
# 定时发送消息
send_message:
<for-send_message>  - time: { send_message.time }
    # 发送到哪些群聊
    groups: { send_message.groups }
    # 发送给哪些好友
    friends: { send_message.friends }
    # 消息模板 可在template文件夹中创建，文件会被git忽略，也可自行填写路径，相对路径相对于终端所在目录
    templatePath: { send_message.templatePath }
</for-send_message>
# 刷新cdn缓存，需要配置tencentCloud
# 消息格式( <>为必填 []为选填 )：
# <命令前缀> [刷新类型 0:刷新变更资源/1:刷新全部资源] [urlEncode 0:关闭 1:开启]
# <url 一行一个，可以是下面的预设，可以是all>
# [url]
# [url]
purge_cdn_cache:
  # 命令发送人 可以是自己
  commandSender: 12345
  # 命令前缀
  command: 刷新cdn
  # 预设，使用 all 可刷新所有
  urls:
    baidu: https://www.baidu.com
    bing: https://www.bing.com
    google: https://google.com
# 数据库备份聊天记录
# 需要配置数据库
# 可配置 图片和语音的保存位置
sql_v2:
  path:
    Image: './data/Image/'
    Voice: './data/Voice/'